#!/usr/bin/env python3
"""
gen_mel_table.py — 產生裝置端 Mel 濾波器組的靜態表（A11）

用途:
    直接呼叫 librosa.filters.mel(htk=False, norm='slaney')（與
    ssi-backlog/tools/reference_mel.py 用完全相同的參數，見 CONTRACTS.md §3.1），
    把係數存成兩種輸出：

    1. mel_filterbank.c / mel_filterbank.h
       裝置端（A12 mic pipeline）用的稀疏 C 表。每個濾波器只存非零 FFT bin
       的起訖與權重，40 個濾波器加起來遠小於 40x257 的密集表。

    2. mel_filterbank.csv
       同一份係數的密集矩陣（40 x 257，逐 bin），供主機端（B14 MFCC 路線，
       在 A10 NO-GO 時是唯一路線；GO 時則用來跟裝置端輸出互驗）直接用
       numpy/pandas 載入比對，不需要重跑 librosa 就能拿到跟裝置端「同一份」
       係數 —— 兩條路線能不能對得上，取決於它們是不是真的用同一份數字。

重跑:
    python3 gen_mel_table.py
    純函式、無隨機性，相同輸入永遠產生相同輸出（bit-for-bit）。

需求: pip install librosa numpy soundfile （見專案根目錄 requirements.txt）
"""
import sys
from pathlib import Path

import numpy as np

try:
    import librosa
except ImportError:
    print("需要 librosa：pip install librosa numpy soundfile", file=sys.stderr)
    raise

# ── 凍結於 CONTRACTS.md §3.1，必須跟 ssi-backlog/tools/reference_mel.py 完全一致 ──
SR = 16000
N_FFT = 512          # 32 ms @ 16 kHz
N_MELS = 40
FMIN = 80.0
FMAX = 8000.0
N_FFT_BINS = N_FFT // 2 + 1  # 257

OUT_DIR = Path(__file__).parent
HEADER_PATH = OUT_DIR / "mel_filterbank.h"
SOURCE_PATH = OUT_DIR / "mel_filterbank.c"
CSV_PATH = OUT_DIR / "mel_filterbank.csv"


def compute_filterbank():
    """回傳 (N_MELS, N_FFT_BINS) float32 密集三角濾波器組。"""
    return librosa.filters.mel(
        sr=SR,
        n_fft=N_FFT,
        n_mels=N_MELS,
        fmin=FMIN,
        fmax=FMAX,
        htk=False,       # ⚠ Slaney，不是 HTK —— 見 CONTRACTS.md §3.1
        norm="slaney",
    ).astype(np.float32)


def to_sparse(fb):
    """把每個濾波器壓成 (start, len, weights) —— 三角濾波器的非零支撐是連續
    的一段 bin，中間不會有零值缺口，所以起訖 + 權重陣列就能無損重建。"""
    filters = []
    for row in fb:
        nz = np.nonzero(row)[0]
        if len(nz) == 0:
            filters.append((0, 0, np.array([], dtype=np.float32)))
            continue
        start, end = int(nz[0]), int(nz[-1])
        assert list(nz) == list(range(start, end + 1)), (
            "濾波器的非零支撐不連續，稀疏 (start,len) 表示法不適用——"
            "這代表 mel 濾波器組不是預期的三角形狀，需要人工檢查"
        )
        filters.append((start, end - start + 1, row[start:end + 1].copy()))
    return filters


def format_float32(x):
    """9 位有效數字的 C float literal：float32 只需要 ~7.2 位十進位數字
    就能無損 round-trip，9 位留有安全餘裕，遠低於驗收條件的 1e-6 誤差。"""
    return f"{x:.9g}f"


def write_c_files(filters):
    total_weights = sum(length for _, length, _ in filters)

    header = f"""#pragma once
/* AUTO-GENERATED by gen_mel_table.py — 不要手改，改參數後重新產生。
 * CONTRACTS.md §3.1 的 Mel 濾波器組（sr=16000, n_fft=512, n_mels=40,
 * fmin=80, fmax=8000, Slaney scale/norm）。 */

#include <stdint.h>

#define MEL_N_FILTERS   {N_MELS}
#define MEL_N_FFT_BINS  {N_FFT_BINS}  /* n_fft/2 + 1 */

/* 一個三角濾波器的稀疏表示：只存非零支撐區間 [start, start+len) 內的權重，
 * 套用在功率譜 power[start .. start+len-1] 上。 */
typedef struct {{
    uint16_t start;
    uint16_t len;
    const float *w;
}} mel_filter_t;

extern const mel_filter_t mel_filterbank[MEL_N_FILTERS];
"""
    HEADER_PATH.write_text(header)

    lines = [
        '/* AUTO-GENERATED by gen_mel_table.py — 不要手改，改參數後重新產生。 */',
        '#include "mel_filterbank.h"',
        '',
    ]
    for i, (start, length, weights) in enumerate(filters):
        if length == 0:
            continue
        vals = ", ".join(format_float32(float(w)) for w in weights)
        lines.append(f"static const float mel_w{i}[{length}] = {{ {vals} }};")
    lines.append("")
    lines.append("const mel_filter_t mel_filterbank[MEL_N_FILTERS] = {")
    for i, (start, length, _weights) in enumerate(filters):
        w_ref = f"mel_w{i}" if length > 0 else "NULL"
        lines.append(f"    {{ {start}, {length}, {w_ref} }},")
    lines.append("};")
    lines.append("")
    SOURCE_PATH.write_text("\n".join(lines))

    table_bytes = total_weights * 4 + N_MELS * 8  # weights + {u16,u16,ptr} per filter
    return total_weights, table_bytes


def verify_roundtrip(fb, filters):
    """把要寫進 C 檔的字串（%.9g，跟 write_c_files 用同一個格式化函式）解析
    回 float，重建密集矩陣，跟 librosa 原始輸出逐元素比對 < 1e-6。這驗證的
    是「寫進原始碼的十進位字串」保真度，不是編譯後的位元組——真正的位元組
    層級確認要編譯上機讀回來，見完成回報的人工驗證項目。"""
    rebuilt = np.zeros_like(fb)
    for i, (start, length, weights) in enumerate(filters):
        for j in range(length):
            rebuilt[i, start + j] = float(format_float32(float(weights[j]))[:-1])
    max_err = np.max(np.abs(rebuilt - fb))
    return max_err


def write_csv(fb):
    np.savetxt(CSV_PATH, fb, delimiter=",", fmt="%.9g")


def main():
    fb = compute_filterbank()
    filters = to_sparse(fb)
    total_weights, table_bytes = write_c_files(filters)
    write_csv(fb)
    max_err = verify_roundtrip(fb, filters)

    print(f"mel_filterbank: {N_MELS} 濾波器, {N_FFT_BINS} FFT bins")
    print(f"稀疏非零項總數: {total_weights}")
    print(f"表大小估計: {table_bytes} bytes ({table_bytes / 1024:.2f} KB)")
    print(f"字串 round-trip 最大誤差: {max_err:.3e}")
    print(f"已寫入: {HEADER_PATH.name}, {SOURCE_PATH.name}, {CSV_PATH.name}")


if __name__ == "__main__":
    main()
