#pragma once
/* AUTO-GENERATED by gen_mel_table.py — 不要手改，改參數後重新產生。
 * CONTRACTS.md §3.1 的 Mel 濾波器組（sr=16000, n_fft=512, n_mels=40,
 * fmin=80, fmax=8000, Slaney scale/norm）。 */

#include <stdint.h>

#define MEL_N_FILTERS   40
#define MEL_N_FFT_BINS  257  /* n_fft/2 + 1 */

/* 一個三角濾波器的稀疏表示：只存非零支撐區間 [start, start+len) 內的權重，
 * 套用在功率譜 power[start .. start+len-1] 上。 */
typedef struct {
    uint16_t start;
    uint16_t len;
    const float *w;
} mel_filter_t;

extern const mel_filter_t mel_filterbank[MEL_N_FILTERS];
